### PR TITLE
Upgrade to 0.5.0

### PR DESCRIPTION
**Pull request by yalh76**
## Solution
- *Upgrade to 0.5.0*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/plume_ynh%20PR60%20(yalh76)/)

### CODE REVIEW

**Comment by igalic** [comment]
BTW, if your package build process allows you to do custom patches, i'd recommend bumping the version in our Cargo.toml files to actually say `0.5.0` — something we forgot to do ourselves before releasing 😅

**Comment by yalh76** [comment]
> 
> 
> BTW, if your package build process allows you to do custom patches, i'd recommend bumping the version in our Cargo.toml files to actually say `0.5.0` — something we forgot to do ourselves before releasing 😅

Oupsi....

The package doesn't build plume but directly use https://github.com/Plume-org/Plume/releases/download/0.5.0/plume-postgres.tar.gz for x86-64

And for arm64, I build it on my own... It took a lot of time. And now it's already done. So, to be consistent with the x86-64 version, i will keep it with cargo.toml version `0.4.0`

PS: in https://github.com/Plume-org/Plume/blob/9aaff1a484e44b98c4e324a4cfce94c3d1ebb5c9/Cargo.toml#L4, version is still `0.4.0`

**Comment by igalic** [comment]
we've decided that the best way forward is to address the issue with automation : https://github.com/Plume-org/Plume/pull/790

**Comment by yalh76** [comment]
> 
> 
> we've decided that the best way forward is to address the issue with automation : [Plume-org/Plume#790](https://github.com/Plume-org/Plume/pull/790)

Did the automation will also provide builds for arm64 and/or armv7 in addition to the x64-64 version provided ?

**Pull request merged**
